install:baseD.c
	 echo "Para que no haya problemas: "
	 echo "sqlite3 Becarios.d para conectarte"
	 echo "Ya en sqlite3 poner .mode column"
	 echo "Y .headers on"
	echo "SELECT * FROM Becarios"
	gcc -Wall -lsqlite3 -g baseD.c -o baseD
